### ISSUE TITLE
Can you do the same for Cygwin OpenSSH?

### ISSUE THREAD

**Issue by rescenic** [rkitover/windows-alt-sshd-msys2#1]
Hi, thanks a lot for the script.
It's working. Can you make the script for Cygwin too?
But with different port? And add automatically exclusion to Windows Firewall.
![msys2](https://i.ibb.co/858JzWt/28-05-2020-661-22-33-55.png)

**Comment by rkitover** [comment]
Sure, I will update the script to detect and support cygwin.

**Comment by rescenic** [comment]
Thank you so much
